In [2]:
%pip install --upgrade pip
# install dependencies and select solver
%pip install -q amplpy matplotlib pandas

SOLVER = "cplex"

from amplpy import AMPL, ampl_notebook

ampl = ampl_notebook(
    modules=["cplex"],  # modules to install
    license_uuid="default",  # license to use
)  # instantiate AMPL object and register magics

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


Widget Javascript not detected.  It may not be installed or enabled properly. Reconnecting the current kernel may help.


In [109]:
import json
import numpy as np
import random
from itertools import combinations

m = AMPL()
m.read("objectives.mod")

m.option["solver"] = SOLVER

m.param["sat_max"] = 6



m.solve()

total_cost = m.get_objective("X_grid")
print("Objective is:", total_cost.get().value())

X_raw = np.array(m.getVariable("X").get_values().to_list())
X = np.empty((4,6,6), dtype=int)
X[X_raw[:,2]-1,X_raw[:,0]-1,X_raw[:,1]-1] = X_raw[:,3]

print(X)


CPLEX 22.1.1.0: optimal integer solution; objective 27
3 MIP simplex iterations
0 branch-and-bound nodes
No basis.
Objective is: 27.0
[[[0 1 1 1 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 1 0 0 0 0]
  [1 1 0 1 0 1]
  [1 1 1 1 0 0]]

 [[0 1 1 0 0 0]
  [0 0 0 0 1 0]
  [0 0 0 0 0 0]
  [0 1 1 0 1 1]
  [1 1 1 1 0 1]
  [0 0 0 0 0 0]]

 [[0 1 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [1 0 0 0 0 0]
  [0 0 0 1 0 0]
  [0 0 0 0 0 0]]]
